name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'  # e.g., v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./desktop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and release
        uses: electron-builder/action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
